# Learn more about it on https://github.com/Azure/functions-action
# Inspiration was found in https://www.aaron-powell.com/posts/2020-01-10-deploying-azure-functions-with-github-actions/

name: Build & Deploy Azure Function

on:
  [push]

env:
  OUTPUT_PATH: ${{ github.workspace }}/.output
  ARTIFACT_NAME: function-app-package

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_VERSION: '3.1.x'
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup .NET v${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Create Azure Function Artifact
      run: dotnet publish ./src/AzureFunctions --configuration Release --output ${{ env.OUTPUT_PATH }}

    - name: Publish Azure Function Artifact
      uses: actions/upload-artifact@v1
      with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.OUTPUT_PATH }}
  deploy:
      runs-on: ubuntu-latest
      needs: [build]
      env:
        AZURE_FUNCTIONAPP_NAME: azure-functions-github-actions
      steps:
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
            name: ${{ env.ARTIFACT_NAME }}
            path: ${{ env.OUTPUT_PATH }}
      - name: Deploy to Azure
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.OUTPUT_PATH }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}